### ISSUE TITLE
3bz fails on SBCL - MAKE-EA was removed

### ISSUE THREAD

**Issue by metayan** [3b/3bz#10]
MAKE-EA was removed in https://github.com/sbcl/sbcl/commit/0a3aad22de39620fd646d3a0771c5d210f5fb5ee

```
debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {1005C802D3}>:
  The function SB-VM::MAKE-EA is undefined.
```
It still works on SBCL 2.0.11, so no panic.

**Comment by 3b** [comment]
From discussions on sbcl-devel mailing list, i think that is a problem in nibbles, which 3bz uses. Hopefully that will be fixed soon.

**Comment by metayan** [comment]
Didn't investigate thoroughly enough before filing the issue. Sorry.
