### ISSUE TITLE
Out-of-bounds writes in `decompress-deflate`

### ISSUE THREAD

**Issue by se-mz** [3b/3bz#16]
The initial and final loops of the `:copy-block` state do not check whether enough space remains in `output-buffer`. Whether this is triggered obviously depends on the chosen buffer size, but an example affecting both loops can be seen when using [this code](https://github.com/se-mz/decompress/issues/1#issuecomment-1478803959) on [this file](https://semelz.de/files/openh264-2.3.1.tar.gz) (warning: 60MB).

**Comment by 3b** [comment]
fixed by #17
