### ISSUE TITLE
Non default *print-case*.

### ISSUE THREAD

**Issue by markcox80** [3b/3bz#9]
Setting `*print-case*` to `:downcase` causes `3bz` to fail.

I am not sure if you want to support the read and print case madness but I think the issue is local to [`DEFUN-WITH-READER-CONTEXTS`](https://github.com/3b/3bz/blob/master/io.lisp#L108) and [`DEFSTRUCT-CACHED`](https://github.com/3b/3bz/blob/master/util.lisp#L6).

**Comment by 3b** [comment]
should be fixed now i think

**Comment by markcox80** [comment]
Thank you!
